#!/bin/env php
<?php

declare(strict_types=1);

use dvikan\SimpleParts\ErrorHandler;
use dvikan\SimpleStaticSiteGenerator\Generator;

if(file_exists(__DIR__ . '/../../autoload.php')) {
    // We are installed as a library
    require __DIR__ . '/../../autoload.php';
} else {
    // We are installed as a project or git cloned
    require __DIR__ . '/vendor/autoload.php';
}

ErrorHandler::create();

if (file_exists('config.php')) {
    $config = require 'config.php';
}

$generator = new Generator($config ?? []);

$generator->generate();
